In [1]:
import torch
import torch.nn as nn


def print_(model):
    for name, params in model.named_parameters():
        print('-->name:', name)
        print('-->para:', params)
        print('-->grad_requires:', params.requires_grad)
        print('-->grad_value:', params.grad)
        print("===")

class simpleModel(nn.Module):
    def __init__(self):
        super(simpleModel, self).__init__()
        self.l = nn.Linear(4,2, bias=False)
    def forward(self,x):
        x = self.l(x)
        return x

def train_step(model, optimizer, x, y):     # 即使没有回传损失仍然可以对模型进行梯度下降并参数更新
    out = model(x)
    loss = torch.nn.CrossEntropyLoss()(out, y)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

x = torch.rand([4,4])
y = torch.rand([4,2])
model = simpleModel()
print_(model)
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
train_step(model, optimizer, x,y)
print_(model)

train_step(model, optimizer, x, y)
print_(model)

-->name: l.weight
-->para: Parameter containing:
tensor([[-0.2236,  0.2460,  0.1775, -0.0706],
        [-0.4351,  0.2742,  0.1009, -0.4755]], requires_grad=True)
-->grad_requires: True
-->grad_value: None
===
-->name: l.weight
-->para: Parameter containing:
tensor([[-0.2246,  0.2450,  0.1765, -0.0716],
        [-0.4341,  0.2752,  0.1019, -0.4745]], requires_grad=True)
-->grad_requires: True
-->grad_value: tensor([[ 0.0226,  0.0026,  0.0528,  0.0205],
        [-0.0226, -0.0026, -0.0528, -0.0205]])
===
-->name: l.weight
-->para: Parameter containing:
tensor([[-0.2256,  0.2440,  0.1755, -0.0726],
        [-0.4331,  0.2762,  0.1029, -0.4735]], requires_grad=True)
-->grad_requires: True
-->grad_value: tensor([[ 0.0223,  0.0022,  0.0523,  0.0201],
        [-0.0223, -0.0022, -0.0523, -0.0201]])
===
