In [27]:
import torch
import torch.nn as nn

class simpleModel(nn.Module):
    def __init__(self) -> None:
        super(simpleModel, self).__init__()
        self.conv = nn.Conv2d(1, 1, 1)
        self.bn = nn.BatchNorm2d(1)
        self.act = nn.ReLU()
    
    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
        x = self.act(x)
        return x


In [30]:
src = simpleModel()
tgt = simpleModel()
scale = torch.tensor(0.1, dtype=torch.float32)

src_dict = src.state_dict()
tgt_dict = tgt.state_dict()
new_tgt = simpleModel()
print("src model:")
print(src.conv.weight)
print("tgt model:")
print(tgt.conv.weight)

param_new = {}
with torch.no_grad():
    for key in tgt_dict.keys():
        if key.split('.')[-1] == "weight" or key.split('.')[-1] == "bias":
            param_new[key] = tgt_dict[key] + scale * src_dict[key]
        else:
            param_new[key] = tgt_dict[key]

new_tgt.load_state_dict(param_new)
print("修改后：")
print(new_tgt.conv.weight)

src model:
Parameter containing:
tensor([[[[-0.1107]]]], requires_grad=True)
tgt model:
Parameter containing:
tensor([[[[0.0794]]]], requires_grad=True)
修改后：
Parameter containing:
tensor([[[[0.0684]]]], requires_grad=True)
